[package]
name = "example_03"
version = "0.1.0"
authors = ["Francisco Moon <francisco.moon@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
